version: "2.0"
services:
  executor:
    build:
      context: .
    command: gunicorn executor.wsgi --workers=9 --log-file=- --log-level=debug --keep-alive=600 --timeout=600 --bind 0.0.0.0:8000

    ports:
      - 8005:8000
    volumes:
      - static_volume:/executor/static
      - media_volume:/executor/media

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/executor/static
      - media_volume:/executor/media
    ports:
      - 81:80
    depends_on:
      - executor


volumes:
  static_volume:
  media_volume: