version: "2.0"
services:
  executor:
    build:
      context: .
    command: gunicorn executor.wsgi --workers=9 --log-file=- --log-level=debug --keep-alive=600 --timeout=600 --bind 0.0.0.0:8000
    depends_on:
      - mysql
    ports:
      - 8005:8005
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 84:80
    depends_on:
      - executor


  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - /etc/mysql.cnf:/app/config/mysql.cnf
      - /var/lib/mysql:/var/lib/mysql


volumes:
  static_volume:
  media_volume: